/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as guestRouteRouteImport } from './routes/(guest)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as authnewUserRouteRouteImport } from './routes/(auth)/(new-user)/route'
import { Route as authexistingUserRouteRouteImport } from './routes/(auth)/(existing-user)/route'
import { Route as guestSigninIndexRouteImport } from './routes/(guest)/signin/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as authexistingUseradminRouteRouteImport } from './routes/(auth)/(existing-user)/(admin)/route'
import { Route as authnewUserWelcomeIndexRouteImport } from './routes/(auth)/(new-user)/welcome/index'
import { Route as authexistingUserKycIndexRouteImport } from './routes/(auth)/(existing-user)/kyc/index'
import { Route as authexistingUserDashboardIndexRouteImport } from './routes/(auth)/(existing-user)/dashboard/index'
import { Route as authexistingUseradminManageIndexRouteImport } from './routes/(auth)/(existing-user)/(admin)/manage/index'

const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const guestRouteRoute = guestRouteRouteImport.update({
  id: '/(guest)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicRouteRoute,
} as any)
const authnewUserRouteRoute = authnewUserRouteRouteImport.update({
  id: '/(new-user)',
  getParentRoute: () => authRouteRoute,
} as any)
const authexistingUserRouteRoute = authexistingUserRouteRouteImport.update({
  id: '/(existing-user)',
  getParentRoute: () => authRouteRoute,
} as any)
const guestSigninIndexRoute = guestSigninIndexRouteImport.update({
  id: '/signin/',
  path: '/signin/',
  getParentRoute: () => guestRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const authexistingUseradminRouteRoute =
  authexistingUseradminRouteRouteImport.update({
    id: '/(admin)',
    getParentRoute: () => authexistingUserRouteRoute,
  } as any)
const authnewUserWelcomeIndexRoute = authnewUserWelcomeIndexRouteImport.update({
  id: '/welcome/',
  path: '/welcome/',
  getParentRoute: () => authnewUserRouteRoute,
} as any)
const authexistingUserKycIndexRoute =
  authexistingUserKycIndexRouteImport.update({
    id: '/kyc/',
    path: '/kyc/',
    getParentRoute: () => authexistingUserRouteRoute,
  } as any)
const authexistingUserDashboardIndexRoute =
  authexistingUserDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => authexistingUserRouteRoute,
  } as any)
const authexistingUseradminManageIndexRoute =
  authexistingUseradminManageIndexRouteImport.update({
    id: '/manage/',
    path: '/manage/',
    getParentRoute: () => authexistingUseradminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof publicIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/signin/': typeof guestSigninIndexRoute
  '/dashboard/': typeof authexistingUserDashboardIndexRoute
  '/kyc/': typeof authexistingUserKycIndexRoute
  '/welcome/': typeof authnewUserWelcomeIndexRoute
  '/manage/': typeof authexistingUseradminManageIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof publicIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/signin': typeof guestSigninIndexRoute
  '/dashboard': typeof authexistingUserDashboardIndexRoute
  '/kyc': typeof authexistingUserKycIndexRoute
  '/welcome': typeof authnewUserWelcomeIndexRoute
  '/manage': typeof authexistingUseradminManageIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authRouteRouteWithChildren
  '/(guest)': typeof guestRouteRouteWithChildren
  '/(public)': typeof publicRouteRouteWithChildren
  '/(auth)/(existing-user)': typeof authexistingUserRouteRouteWithChildren
  '/(auth)/(new-user)': typeof authnewUserRouteRouteWithChildren
  '/(public)/': typeof publicIndexRoute
  '/(auth)/(existing-user)/(admin)': typeof authexistingUseradminRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(guest)/signin/': typeof guestSigninIndexRoute
  '/(auth)/(existing-user)/dashboard/': typeof authexistingUserDashboardIndexRoute
  '/(auth)/(existing-user)/kyc/': typeof authexistingUserKycIndexRoute
  '/(auth)/(new-user)/welcome/': typeof authnewUserWelcomeIndexRoute
  '/(auth)/(existing-user)/(admin)/manage/': typeof authexistingUseradminManageIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/auth/$'
    | '/signin/'
    | '/dashboard/'
    | '/kyc/'
    | '/welcome/'
    | '/manage/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/auth/$'
    | '/signin'
    | '/dashboard'
    | '/kyc'
    | '/welcome'
    | '/manage'
  id:
    | '__root__'
    | '/(auth)'
    | '/(guest)'
    | '/(public)'
    | '/(auth)/(existing-user)'
    | '/(auth)/(new-user)'
    | '/(public)/'
    | '/(auth)/(existing-user)/(admin)'
    | '/api/auth/$'
    | '/(guest)/signin/'
    | '/(auth)/(existing-user)/dashboard/'
    | '/(auth)/(existing-user)/kyc/'
    | '/(auth)/(new-user)/welcome/'
    | '/(auth)/(existing-user)/(admin)/manage/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authRouteRoute: typeof authRouteRouteWithChildren
  guestRouteRoute: typeof guestRouteRouteWithChildren
  publicRouteRoute: typeof publicRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(guest)': {
      id: '/(guest)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof guestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(auth)/(new-user)': {
      id: '/(auth)/(new-user)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authnewUserRouteRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/(existing-user)': {
      id: '/(auth)/(existing-user)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authexistingUserRouteRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(guest)/signin/': {
      id: '/(guest)/signin/'
      path: '/signin'
      fullPath: '/signin/'
      preLoaderRoute: typeof guestSigninIndexRouteImport
      parentRoute: typeof guestRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/(existing-user)/(admin)': {
      id: '/(auth)/(existing-user)/(admin)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authexistingUseradminRouteRouteImport
      parentRoute: typeof authexistingUserRouteRoute
    }
    '/(auth)/(new-user)/welcome/': {
      id: '/(auth)/(new-user)/welcome/'
      path: '/welcome'
      fullPath: '/welcome/'
      preLoaderRoute: typeof authnewUserWelcomeIndexRouteImport
      parentRoute: typeof authnewUserRouteRoute
    }
    '/(auth)/(existing-user)/kyc/': {
      id: '/(auth)/(existing-user)/kyc/'
      path: '/kyc'
      fullPath: '/kyc/'
      preLoaderRoute: typeof authexistingUserKycIndexRouteImport
      parentRoute: typeof authexistingUserRouteRoute
    }
    '/(auth)/(existing-user)/dashboard/': {
      id: '/(auth)/(existing-user)/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof authexistingUserDashboardIndexRouteImport
      parentRoute: typeof authexistingUserRouteRoute
    }
    '/(auth)/(existing-user)/(admin)/manage/': {
      id: '/(auth)/(existing-user)/(admin)/manage/'
      path: '/manage'
      fullPath: '/manage/'
      preLoaderRoute: typeof authexistingUseradminManageIndexRouteImport
      parentRoute: typeof authexistingUseradminRouteRoute
    }
  }
}

interface authexistingUseradminRouteRouteChildren {
  authexistingUseradminManageIndexRoute: typeof authexistingUseradminManageIndexRoute
}

const authexistingUseradminRouteRouteChildren: authexistingUseradminRouteRouteChildren =
  {
    authexistingUseradminManageIndexRoute:
      authexistingUseradminManageIndexRoute,
  }

const authexistingUseradminRouteRouteWithChildren =
  authexistingUseradminRouteRoute._addFileChildren(
    authexistingUseradminRouteRouteChildren,
  )

interface authexistingUserRouteRouteChildren {
  authexistingUseradminRouteRoute: typeof authexistingUseradminRouteRouteWithChildren
  authexistingUserDashboardIndexRoute: typeof authexistingUserDashboardIndexRoute
  authexistingUserKycIndexRoute: typeof authexistingUserKycIndexRoute
}

const authexistingUserRouteRouteChildren: authexistingUserRouteRouteChildren = {
  authexistingUseradminRouteRoute: authexistingUseradminRouteRouteWithChildren,
  authexistingUserDashboardIndexRoute: authexistingUserDashboardIndexRoute,
  authexistingUserKycIndexRoute: authexistingUserKycIndexRoute,
}

const authexistingUserRouteRouteWithChildren =
  authexistingUserRouteRoute._addFileChildren(
    authexistingUserRouteRouteChildren,
  )

interface authnewUserRouteRouteChildren {
  authnewUserWelcomeIndexRoute: typeof authnewUserWelcomeIndexRoute
}

const authnewUserRouteRouteChildren: authnewUserRouteRouteChildren = {
  authnewUserWelcomeIndexRoute: authnewUserWelcomeIndexRoute,
}

const authnewUserRouteRouteWithChildren =
  authnewUserRouteRoute._addFileChildren(authnewUserRouteRouteChildren)

interface authRouteRouteChildren {
  authexistingUserRouteRoute: typeof authexistingUserRouteRouteWithChildren
  authnewUserRouteRoute: typeof authnewUserRouteRouteWithChildren
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authexistingUserRouteRoute: authexistingUserRouteRouteWithChildren,
  authnewUserRouteRoute: authnewUserRouteRouteWithChildren,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface guestRouteRouteChildren {
  guestSigninIndexRoute: typeof guestSigninIndexRoute
}

const guestRouteRouteChildren: guestRouteRouteChildren = {
  guestSigninIndexRoute: guestSigninIndexRoute,
}

const guestRouteRouteWithChildren = guestRouteRoute._addFileChildren(
  guestRouteRouteChildren,
)

interface publicRouteRouteChildren {
  publicIndexRoute: typeof publicIndexRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicIndexRoute: publicIndexRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authRouteRoute: authRouteRouteWithChildren,
  guestRouteRoute: guestRouteRouteWithChildren,
  publicRouteRoute: publicRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
