/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as unauthenticatedRoutesRouteRouteImport } from './routes/(unauthenticated-routes)/route'
import { Route as authenticatedRoutesRouteRouteImport } from './routes/(authenticated-routes)/route'
import { Route as authenticatedRoutesIndexRouteImport } from './routes/(authenticated-routes)/index'
import { Route as unauthenticatedRoutesSignupIndexRouteImport } from './routes/(unauthenticated-routes)/signup/index'
import { Route as unauthenticatedRoutesLoginIndexRouteImport } from './routes/(unauthenticated-routes)/login/index'
import { Route as authenticatedRoutesManageIndexRouteImport } from './routes/(authenticated-routes)/manage/index'
import { Route as authenticatedRoutesKycIndexRouteImport } from './routes/(authenticated-routes)/kyc/index'

const unauthenticatedRoutesRouteRoute =
  unauthenticatedRoutesRouteRouteImport.update({
    id: '/(unauthenticated-routes)',
    getParentRoute: () => rootRouteImport,
  } as any)
const authenticatedRoutesRouteRoute =
  authenticatedRoutesRouteRouteImport.update({
    id: '/(authenticated-routes)',
    getParentRoute: () => rootRouteImport,
  } as any)
const authenticatedRoutesIndexRoute =
  authenticatedRoutesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authenticatedRoutesRouteRoute,
  } as any)
const unauthenticatedRoutesSignupIndexRoute =
  unauthenticatedRoutesSignupIndexRouteImport.update({
    id: '/signup/',
    path: '/signup/',
    getParentRoute: () => unauthenticatedRoutesRouteRoute,
  } as any)
const unauthenticatedRoutesLoginIndexRoute =
  unauthenticatedRoutesLoginIndexRouteImport.update({
    id: '/login/',
    path: '/login/',
    getParentRoute: () => unauthenticatedRoutesRouteRoute,
  } as any)
const authenticatedRoutesManageIndexRoute =
  authenticatedRoutesManageIndexRouteImport.update({
    id: '/manage/',
    path: '/manage/',
    getParentRoute: () => authenticatedRoutesRouteRoute,
  } as any)
const authenticatedRoutesKycIndexRoute =
  authenticatedRoutesKycIndexRouteImport.update({
    id: '/kyc/',
    path: '/kyc/',
    getParentRoute: () => authenticatedRoutesRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof authenticatedRoutesIndexRoute
  '/kyc/': typeof authenticatedRoutesKycIndexRoute
  '/manage/': typeof authenticatedRoutesManageIndexRoute
  '/login/': typeof unauthenticatedRoutesLoginIndexRoute
  '/signup/': typeof unauthenticatedRoutesSignupIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof authenticatedRoutesIndexRoute
  '/kyc': typeof authenticatedRoutesKycIndexRoute
  '/manage': typeof authenticatedRoutesManageIndexRoute
  '/login': typeof unauthenticatedRoutesLoginIndexRoute
  '/signup': typeof unauthenticatedRoutesSignupIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(authenticated-routes)': typeof authenticatedRoutesRouteRouteWithChildren
  '/(unauthenticated-routes)': typeof unauthenticatedRoutesRouteRouteWithChildren
  '/(authenticated-routes)/': typeof authenticatedRoutesIndexRoute
  '/(authenticated-routes)/kyc/': typeof authenticatedRoutesKycIndexRoute
  '/(authenticated-routes)/manage/': typeof authenticatedRoutesManageIndexRoute
  '/(unauthenticated-routes)/login/': typeof unauthenticatedRoutesLoginIndexRoute
  '/(unauthenticated-routes)/signup/': typeof unauthenticatedRoutesSignupIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/kyc/' | '/manage/' | '/login/' | '/signup/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/kyc' | '/manage' | '/login' | '/signup'
  id:
    | '__root__'
    | '/(authenticated-routes)'
    | '/(unauthenticated-routes)'
    | '/(authenticated-routes)/'
    | '/(authenticated-routes)/kyc/'
    | '/(authenticated-routes)/manage/'
    | '/(unauthenticated-routes)/login/'
    | '/(unauthenticated-routes)/signup/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authenticatedRoutesRouteRoute: typeof authenticatedRoutesRouteRouteWithChildren
  unauthenticatedRoutesRouteRoute: typeof unauthenticatedRoutesRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(unauthenticated-routes)': {
      id: '/(unauthenticated-routes)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof unauthenticatedRoutesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated-routes)': {
      id: '/(authenticated-routes)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedRoutesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated-routes)/': {
      id: '/(authenticated-routes)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authenticatedRoutesIndexRouteImport
      parentRoute: typeof authenticatedRoutesRouteRoute
    }
    '/(unauthenticated-routes)/signup/': {
      id: '/(unauthenticated-routes)/signup/'
      path: '/signup'
      fullPath: '/signup/'
      preLoaderRoute: typeof unauthenticatedRoutesSignupIndexRouteImport
      parentRoute: typeof unauthenticatedRoutesRouteRoute
    }
    '/(unauthenticated-routes)/login/': {
      id: '/(unauthenticated-routes)/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof unauthenticatedRoutesLoginIndexRouteImport
      parentRoute: typeof unauthenticatedRoutesRouteRoute
    }
    '/(authenticated-routes)/manage/': {
      id: '/(authenticated-routes)/manage/'
      path: '/manage'
      fullPath: '/manage/'
      preLoaderRoute: typeof authenticatedRoutesManageIndexRouteImport
      parentRoute: typeof authenticatedRoutesRouteRoute
    }
    '/(authenticated-routes)/kyc/': {
      id: '/(authenticated-routes)/kyc/'
      path: '/kyc'
      fullPath: '/kyc/'
      preLoaderRoute: typeof authenticatedRoutesKycIndexRouteImport
      parentRoute: typeof authenticatedRoutesRouteRoute
    }
  }
}

interface authenticatedRoutesRouteRouteChildren {
  authenticatedRoutesIndexRoute: typeof authenticatedRoutesIndexRoute
  authenticatedRoutesKycIndexRoute: typeof authenticatedRoutesKycIndexRoute
  authenticatedRoutesManageIndexRoute: typeof authenticatedRoutesManageIndexRoute
}

const authenticatedRoutesRouteRouteChildren: authenticatedRoutesRouteRouteChildren =
  {
    authenticatedRoutesIndexRoute: authenticatedRoutesIndexRoute,
    authenticatedRoutesKycIndexRoute: authenticatedRoutesKycIndexRoute,
    authenticatedRoutesManageIndexRoute: authenticatedRoutesManageIndexRoute,
  }

const authenticatedRoutesRouteRouteWithChildren =
  authenticatedRoutesRouteRoute._addFileChildren(
    authenticatedRoutesRouteRouteChildren,
  )

interface unauthenticatedRoutesRouteRouteChildren {
  unauthenticatedRoutesLoginIndexRoute: typeof unauthenticatedRoutesLoginIndexRoute
  unauthenticatedRoutesSignupIndexRoute: typeof unauthenticatedRoutesSignupIndexRoute
}

const unauthenticatedRoutesRouteRouteChildren: unauthenticatedRoutesRouteRouteChildren =
  {
    unauthenticatedRoutesLoginIndexRoute: unauthenticatedRoutesLoginIndexRoute,
    unauthenticatedRoutesSignupIndexRoute:
      unauthenticatedRoutesSignupIndexRoute,
  }

const unauthenticatedRoutesRouteRouteWithChildren =
  unauthenticatedRoutesRouteRoute._addFileChildren(
    unauthenticatedRoutesRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  authenticatedRoutesRouteRoute: authenticatedRoutesRouteRouteWithChildren,
  unauthenticatedRoutesRouteRoute: unauthenticatedRoutesRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
